### ISSUE TITLE
Error when deploying branch

### ISSUE THREAD

**Issue by kaneda-fr** [idoberko2/dokku-deploy-github-action#4]
Hi,

I'm trying to deploy a branch and get the following error message:

GIT_COMMAND=git push deploy 69a6341aa401f37a24739d74eabf3fe292c5cadc:refs/heads/refs/heads/v0.1:master 
error: src refspec 69a6341aa401f37a24739d74eabf3fe292c5cadc:refs/heads/refs/heads/v0.1 does not match any.
error: failed to push some refs to 'dokku@mydomain.me:test-app'

I get the same message when trying the git push manually, so I guess it's an issue with git and the reference syntax,

Is it working on your side ?

**Comment by kaneda-fr** [comment]
After more testing I found out that this works when removing the branch reference such as:
git push -f deploy 69a6341aa401f37a24739d74eabf3fe292c5cadc:master

I'll create a patch for that.

**Comment by idoberko2** [comment]
Hey @kaneda-fr, glad to hear you managed to get pass this. Do you need any more assistance?

**Comment by idoberko2** [comment]
Closing as stale
