### ISSUE TITLE
fatal: Could not read from remote repository. / Documentation 

### ISSUE THREAD

**Issue by chrisjsimpson** [idoberko2/dokku-deploy-github-action#6]
Hi, 

Thanks for creating this. 

Locally I can push to to dokku

e.g. `git push deploy a35a0c163cba7bf76ad8f4a7723f25eb453e80c0:refs/heads/master` is successful from my local machine, and dokku generates a new build.

However in the pipeline I'm seeing the following error:

Example failing pipeline
https://github.com/chrisjsimpson/fastapi/runs/993763193?check_suite_focus=true#step:4:18

For testing, I have set-up secrets using the same private key (`SSH_PRIVATE_KEY`) 

I'm probably missing some key steps on the dokku server in relation to authorised keys. 

Any additional documentation on the dokku setup required is much appreciated.

**Comment by chrisjsimpson** [comment]
Sorry. I should read the logs more clearly: https://github.com/chrisjsimpson/fastapi/runs/993763193?check_suite_focus=true#step:4:9

My key required a password, which obliviously won't work the pipeline.

This could be checked for in the pipeline action, but really it's user error.  

Documentation update PR: https://github.com/idoberko2/dokku-deploy-github-action/pull/7

**Comment by idoberko2** [comment]
Thanks for that @chrisjsimpson!
